language: node_js
node_js:
  - "7"

node_js: 
  - node

before_script:
  - npm install -g gulp-cli
  
install: 
  - npm ci

script: 
  # - npm run lint
  - npm test
  # - npm start

notifications: 
  email: false